// FILE: packages/providers/src/llm/mock.ts
import { LLMProvider } from "../interfaces";
import { ContentAnalysis, GeneratedScript, SceneSchema } from "@studio/shared";

export class MockLLMProvider implements LLMProvider {
  name = "mock";

  async chatJSON<T>(_s: string, _u: string): Promise<T> { return {} as T; }

  async analyzeContent(input: string): Promise<ContentAnalysis> {
    return {
      main_topic: input.slice(0, 80),
      key_points: ["Key point A", "Key point B", "Key point C"],
      claims: [{ text: "Example claim extracted from input", confidence: "estimate" }],
      entities: [], important_numbers: [], emotional_tone: "curious",
      target_audience: "general audience",
      likely_viewer_questions: ["Why does this matter?", "How does this affect me?"],
      potential_hooks: [`What if everything you knew about "${input.slice(0, 40)}" was wrong?`],
      visual_opportunities: ["diagram", "timeline", "comparison chart"],
      uncertain_claims: [],
    };
  }

  async generateScript(params: { analysis: ContentAnalysis; durationSeconds?: number }): Promise<GeneratedScript> {
    const topic = params.analysis.main_topic;
    const sections: GeneratedScript["sections"] = [
      { type: "hook", text: `What if I told you the truth about ${topic} would surprise you? Stay with me.` },
      { type: "intro", text: `Today we're breaking down ${topic} in a way that actually makes sense.` },
      { type: "body", text: `First, let's look at ${params.analysis.key_points[0]}. This changes everything you thought you knew.` },
      { type: "body", text: `Next, consider ${params.analysis.key_points[1] || "the second angle"}. It's more surprising than it sounds.` },
      { type: "engagement", text: `Quick question — what would you guess happens next? Drop your answer in the comments.` },
      { type: "body", text: `Here's the final piece: ${params.analysis.key_points[2] || "the conclusion"}.` },
      { type: "ending", text: `So now you know the real story behind ${topic}. If you want the deeper dive, the next video covers exactly that. See you there.` },
    ];
    const full_text = sections.map((s) => s.text).join(" ");
    return {
      title_candidates: [`The Truth About ${topic}`, `${topic}: What Nobody Tells You`, `Why ${topic} Matters More Than You Think`],
      sections, full_text,
      estimated_duration_seconds: params.durationSeconds || Math.round(full_text.split(" ").length / 2.5),
    };
  }

  async reviseForRetention(script: GeneratedScript): Promise<GeneratedScript> { return script; }

  async planScenes(script: GeneratedScript, targetDurationSec: number): Promise<SceneSchema[]> {
    const sentences = script.full_text.split(/(?<=[.?!])\s+/).filter(Boolean);
    const per = targetDurationSec / sentences.length;
    return sentences.map((s, i) => ({
      scene_id: i + 1,
      start_time: Math.round(i * per),
      end_time: Math.round((i + 1) * per),
      narration: s,
      visual_type: i % 3 === 0 ? "avatar" : i % 3 === 1 ? "b_roll_image" : "infographic",
      visual_prompt: `Visual representing: ${s}`,
      on_screen_text: s.length < 40 ? s : undefined,
      camera: i % 2 === 0 ? "slow_zoom_in" : "static",
      transition: i === 0 ? "cut" : "fade",
      music_cue: "upbeat-curious",
      sound_effect: i % 4 === 0 ? "whoosh" : undefined,
      caption: s,
      interaction: s.toLowerCase().includes("guess") ? "pause_guess" : "none",
      keywords_to_highlight: [],
    }));
  }

  async critiqueRetention(): Promise<{ score: number; notes: string }> {
    return { score: 72, notes: "Mock heuristic score. Connect a real LLM provider for actual analysis." };
  }

  async generateMetadata(script: GeneratedScript) {
    return {
      titles: script.title_candidates,
      description: `${script.full_text.slice(0, 200)}...\n\nGenerated by AI YouTube Studio.`,
      tags: ["ai", "education", "explainer"],
      hashtags: ["#shorts", "#explainer", "#ai"],
      chapters: [{ time: 0, title: "Intro" }, { time: Math.round(script.estimated_duration_seconds / 2), title: "Main Point" }],
    };
  }
}